spring.datasource.url=jdbc:postgresql://localhost:5432/store_project_bd
spring.datasource.username=postgres
spring.datasource.password=B4lenci@ga

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true