ALTER TABLE clientes ALTER COLUMN cpf DROP NOT NULL;
ALTER TABLE clientes ALTER COLUMN cpf TYPE VARCHAR(11);

ALTER TABLE clientes ALTER COLUMN cnpj DROP NOT NULL;
ALTER TABLE clientes ALTER COLUMN cnpj TYPE VARCHAR(14);